name: E2E Tests on Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'FrontendNextjs/**'
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL to test'
        required: false
        default: 'https://gestor-de-presupuesto.vercel.app'

jobs:
  e2e-test-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Wait for Vercel Deployment
        uses: tj-actions/vercel-wait@v1
        id: vercel-deploy
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: ${{ github.sha }}

      - name: Install dependencies
        working-directory: ./e2e-test
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./e2e-test
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./e2e-test
        env:
          E2E_TARGET_URL: ${{ steps.vercel-deploy.outputs.deployment-url }}
        run: npx playwright test
